
name: certbot-standalone-nfq
summary: Certbot HTTP authenticator that works with any web server.
description: Certbot HTTP authenticator that works with any web server.
website: https://github.com/alexzorin/certbot-standalone-nfq
license: GPL-2.0
confinement: strict
grade: stable
base: core24
adopt-info: certbot-standalone-nfq
platforms:
  amd64:
  arm64:
    build-on: [arm64]
  armhf:
    build-on: [armhf]
parts:
  certbot-standalone-nfq:
    plugin: python
    source: .
    override-pull: |
        craftctl default
        craftctl set version=`git describe --tags`
    build-environment:
      - SNAP_BUILD: "True"
    build-packages:
      - gcc
      - git
      - build-essential
      - libffi-dev
      - python3-dev
  certbot-metadata:
    plugin: dump
    source: .
    stage: [setup.py, certbot-shared]
    override-pull: |
        craftctl default
        mkdir -p $CRAFT_PART_SRC/certbot-shared
slots:
  certbot:
    interface: content
    content: certbot-1
    read:
      - $SNAP/lib/python3.12/site-packages

plugs:
  certbot-metadata:
    interface: content
    content: metadata-1
    target: $SNAP/certbot-shared
